-- Catalog: clothes / hats
-- Prop slot 0 (PROP_MAP.hats).

_InventarioCatalogRegistry:add({
    {
        id          = 'hats_basic_cap_01',
        name        = 'Bone Basico',
        category    = 'clothes',
        subcategory = 'hats',
        rarity      = 'common',
        price       = nil,
        purchasable = false,
        image       = 'images/inventario/hats_basic_cap_01.png',
        metadata    = {
            kind     = 'prop',
            slot_id  = 0,
            drawable = 0,
            texture  = 0,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'hats_beanie_red_01',
        name        = 'Touca Vermelha',
        category    = 'clothes',
        subcategory = 'hats',
        rarity      = 'rare',
        price       = 80,
        purchasable = true,
        image       = 'images/inventario/hats_beanie_red_01.png',
        metadata    = {
            kind     = 'prop',
            slot_id  = 0,
            drawable = 1,
            texture  = 0,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'hats_helmet_tactical_01',
        name        = 'Capacete Tatico',
        category    = 'clothes',
        subcategory = 'hats',
        rarity      = 'epic',
        price       = 300,
        purchasable = true,
        image       = 'images/inventario/hats_helmet_tactical_01.png',
        metadata    = {
            kind     = 'prop',
            slot_id  = 0,
            drawable = 2,
            texture  = 0,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'hats_crown_gold_01',
        name        = 'Coroa Dourada',
        category    = 'clothes',
        subcategory = 'hats',
        rarity      = 'legendary',
        price       = 900,
        purchasable = true,
        image       = 'images/inventario/hats_crown_gold_01.png',
        metadata    = {
            kind     = 'prop',
            slot_id  = 0,
            drawable = 3,
            texture  = 1,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'hats_neon_visor_01',
        name        = 'Viseira Neon',
        category    = 'clothes',
        subcategory = 'hats',
        rarity      = 'mythic',
        price       = 1800,
        purchasable = true,
        image       = 'images/inventario/hats_neon_visor_01.png',
        metadata    = {
            kind     = 'prop',
            slot_id  = 0,
            drawable = 5,
            texture  = 2,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
})
