-- Catalog: clothes / pants
-- Component slot 4 (COMPONENT_MAP.legs).

_InventarioCatalogRegistry:add({
    {
        id          = 'pants_basic_jeans_01',
        name        = 'Calca Jeans',
        category    = 'clothes',
        subcategory = 'pants',
        rarity      = 'common',
        price       = nil,
        purchasable = false,
        image       = 'images/inventario/pants_basic_jeans_01.png',
        metadata    = {
            kind     = 'component',
            slot_id  = 4,
            drawable = 0,
            texture  = 0,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'pants_cargo_green_01',
        name        = 'Cargo Verde',
        category    = 'clothes',
        subcategory = 'pants',
        rarity      = 'rare',
        price       = 100,
        purchasable = true,
        image       = 'images/inventario/pants_cargo_green_01.png',
        metadata    = {
            kind     = 'component',
            slot_id  = 4,
            drawable = 1,
            texture  = 0,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'pants_track_black_01',
        name        = 'Calca Esportiva Preta',
        category    = 'clothes',
        subcategory = 'pants',
        rarity      = 'epic',
        price       = 250,
        purchasable = true,
        image       = 'images/inventario/pants_track_black_01.png',
        metadata    = {
            kind     = 'component',
            slot_id  = 4,
            drawable = 2,
            texture  = 1,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'pants_combat_camo_01',
        name        = 'Calca Camuflada',
        category    = 'clothes',
        subcategory = 'pants',
        rarity      = 'legendary',
        price       = 750,
        purchasable = true,
        image       = 'images/inventario/pants_combat_camo_01.png',
        metadata    = {
            kind     = 'component',
            slot_id  = 4,
            drawable = 3,
            texture  = 0,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'pants_neon_pants_01',
        name        = 'Calca Neon',
        category    = 'clothes',
        subcategory = 'pants',
        rarity      = 'mythic',
        price       = 1500,
        purchasable = true,
        image       = 'images/inventario/pants_neon_pants_01.png',
        metadata    = {
            kind     = 'component',
            slot_id  = 4,
            drawable = 5,
            texture  = 2,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
})
