-- Catalog: clothes / tops
-- Component slot 11 (COMPONENT_MAP.tops). Drawables 0..5 picked as realistic
-- defaults for mp_m_freemode_01; the model field is informational only — the
-- applier uses the live ped model regardless.

_InventarioCatalogRegistry:add({
    {
        id          = 'tops_basic_white_tee_01',
        name        = 'Camiseta Branca',
        category    = 'clothes',
        subcategory = 'tops',
        rarity      = 'common',
        price       = nil,
        purchasable = false,
        image       = 'images/inventario/tops_basic_white_tee_01.png',
        metadata    = {
            kind     = 'component',
            slot_id  = 11,
            drawable = 0,
            texture  = 0,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'tops_red_hoodie_01',
        name        = 'Hoodie Vermelho',
        category    = 'clothes',
        subcategory = 'tops',
        rarity      = 'rare',
        price       = 100,
        purchasable = true,
        image       = 'images/inventario/tops_red_hoodie_01.png',
        metadata    = {
            kind     = 'component',
            slot_id  = 11,
            drawable = 1,
            texture  = 0,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'tops_black_jacket_01',
        name        = 'Jaqueta Preta',
        category    = 'clothes',
        subcategory = 'tops',
        rarity      = 'epic',
        price       = 250,
        purchasable = true,
        image       = 'images/inventario/tops_black_jacket_01.png',
        metadata    = {
            kind     = 'component',
            slot_id  = 11,
            drawable = 2,
            texture  = 1,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'tops_gold_vest_01',
        name        = 'Colete Dourado',
        category    = 'clothes',
        subcategory = 'tops',
        rarity      = 'legendary',
        price       = 750,
        purchasable = true,
        image       = 'images/inventario/tops_gold_vest_01.png',
        metadata    = {
            kind     = 'component',
            slot_id  = 11,
            drawable = 3,
            texture  = 2,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
    {
        id          = 'tops_neon_jersey_01',
        name        = 'Camisa Neon',
        category    = 'clothes',
        subcategory = 'tops',
        rarity      = 'mythic',
        price       = 1500,
        purchasable = true,
        image       = 'images/inventario/tops_neon_jersey_01.png',
        metadata    = {
            kind     = 'component',
            slot_id  = 11,
            drawable = 5,
            texture  = 0,
            palette  = 0,
            model    = 'mp_m_freemode_01',
        },
    },
})
