-- Catalog: vehicle_skin / default
-- Applied via stateBag on the vehicle entity; visible to all clients.

_InventarioCatalogRegistry:add({
    {
        id          = 'vehicle_kuruma_stock_01',
        name        = 'Kuruma Padrao',
        category    = 'vehicle_skin',
        subcategory = 'default',
        rarity      = 'common',
        price       = nil,
        purchasable = false,
        image       = 'images/inventario/vehicle_kuruma_stock_01.png',
        metadata    = {
            vehicle_model   = 'kuruma',
            livery          = 0,
            primary_color   = 0,
            secondary_color = 0,
            mod_kit         = 0,
            wheel_type      = nil,
        },
    },
    {
        id          = 'vehicle_kuruma_red_01',
        name        = 'Kuruma Vermelho',
        category    = 'vehicle_skin',
        subcategory = 'default',
        rarity      = 'rare',
        price       = 300,
        purchasable = true,
        image       = 'images/inventario/vehicle_kuruma_red_01.png',
        metadata    = {
            vehicle_model   = 'kuruma',
            livery          = 0,
            primary_color   = 27,
            secondary_color = 0,
            mod_kit         = 0,
            wheel_type      = nil,
        },
    },
    {
        id          = 'vehicle_kuruma_carbon_01',
        name        = 'Kuruma Carbon',
        category    = 'vehicle_skin',
        subcategory = 'default',
        rarity      = 'epic',
        price       = 600,
        purchasable = true,
        image       = 'images/inventario/vehicle_kuruma_carbon_01.png',
        metadata    = {
            vehicle_model   = 'kuruma',
            livery          = 1,
            primary_color   = 0,
            secondary_color = 0,
            mod_kit         = 0,
            wheel_type      = 7,
        },
    },
    {
        id          = 'vehicle_kuruma_gold_01',
        name        = 'Kuruma Dourado',
        category    = 'vehicle_skin',
        subcategory = 'default',
        rarity      = 'legendary',
        price       = 1500,
        purchasable = true,
        image       = 'images/inventario/vehicle_kuruma_gold_01.png',
        metadata    = {
            vehicle_model   = 'kuruma',
            livery          = 2,
            primary_color   = 112,
            secondary_color = 112,
            mod_kit         = 0,
            wheel_type      = 7,
        },
    },
    {
        id          = 'vehicle_kuruma_neon_01',
        name        = 'Kuruma Neon',
        category    = 'vehicle_skin',
        subcategory = 'default',
        rarity      = 'mythic',
        price       = 3000,
        purchasable = true,
        image       = 'images/inventario/vehicle_kuruma_neon_01.png',
        metadata    = {
            vehicle_model   = 'kuruma',
            livery          = 3,
            primary_color   = 92,
            secondary_color = 145,
            mod_kit         = 0,
            wheel_type      = 7,
        },
    },
})
